### ISSUE TITLE
Unable to use array notation while passing values to modal controller.

### ISSUE THREAD

**Issue by raghuvenmarathoor** [dwmkerr/angular-modal-service#104]
This is the code of the controller to show modal dialog in my app

       myApp.controller('addUserCtrl',['$timeout', '$scope', function($timeout,
	    $scope, currentUserParams) {
	  $scope.user = {}
	  $scope.user = currentUserParams;
	  $scope.close = function(result) {
	    if (result === 'add') {
	      $scope.user.action = 'add';
	      $scope.user.ACTIVE = true;
	      close($scope.user, 500);
	    } else {
	      close(result, 500);
	    }
	  };
	  
	}]); 

and this is how I am calling this controller

    $scope.addUser = function() {
		console.log(JSON.stringify($scope.currentUserParams));
	    ModalService.showModal({
	      templateUrl : 'js/modules/user/template/adduser.html',
	      controller : "addUserCtrl",
	      inputs:{
	    	  "currentUserParams": $scope.currentUserParams
	      }
	    }).then(function(modal) {
	      modal.element.modal();
	      modal.close.then(function(result) {
	        if (result !== undefined && result.action === 'add') {
	          delete result.action;
	          console.log('adding');
	          console.log(result);
	          
	          });
	        }
	      }); 
	    });
	  };

problem is that I am not getting the values for the parameter currentUserParams in modal controller. It works fine if I am not using an array notation though. I'm relatively new to angularjs and I think I am missing something.

**Comment by raghuvenmarathoor** [comment]
that was a stupid mistake. I forgot to add dependency to parameter

**Comment by xavadu** [comment]
@raghuvenmarathoor that is something old, but what do you mean with "I forgot to add dependency to parameter" ? which dependency?

**Comment by raghuvenmarathoor** [comment]
@xavadu  I don't remember exactly. But, my assumption is that the dependency array in my code was ('$timeout', '$scope', ) instead it should be ('$timeout', '$scope','currentUserParams').

**Comment by xavadu** [comment]
Thanks, I have it working, and it was the issue, I will update your code with that change for future reference:


```
$scope.addUser = function() {
    console.log(JSON.stringify($scope.currentUserParams));
    ModalService.showModal({
      templateUrl : 'js/modules/user/template/adduser.html',
      controller : "addUserCtrl",
      inputs:{
          "currentUserParams": $scope.currentUserParams,
           "otherInput": 'foobar'
      }
    }).then(function(modal) {
      modal.element.modal();
      modal.close.then(function(result) {
        if (result !== undefined && result.action === 'add') {
          delete result.action;
          console.log('adding');
          console.log(result);

          });
        }
      }); 
    });
  };

// ..

 myApp.controller('addUserCtrl',['$timeout', '$scope', 'currentUserParams', 'otherInput', function($timeout,
    $scope, currentUserParams, otherInput) {
  $scope.user = {}
  $scope.user = currentUserParams;
  $scope.close = function(result) {
    if (result === 'add') {
      $scope.user.action = 'add';
      $scope.user.ACTIVE = true;
      close($scope.user, 500);
    } else {
      close(result, 500);
    }
  };

}]); 
```
