### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by dderiso** [dwmkerr/angular-modal-service#105]
Thanks @dwmkerr for this great library. One of our devs wanted to use this, but it's unclear if this is still being maintained. Any comments would be appreciated. Thanks again for contributing this.

**Comment by dwmkerr** [comment]
Hi @dderiso it's still being maintained but I'm on an extremely hectic project at the moment, it'll be a week or so before I can process any of the PRs!

**Comment by dderiso** [comment]
@dwmkerr No worries, I imagine McKinsey keeps you busy :) . Looking forward to the updates, thanks again for the great library.

**Comment by dwmkerr** [comment]
Cheers! With any luck in the next few days I'll be able to get on top of
the issue backlog :S
