### ISSUE TITLE
Possible bug: Open another modal inside the parent modal

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#106]
I've a problem when I use a modal and then I open another modal inside it. 

When I close the child modal, the css "modal-open" is removed in body class, then the parent model is not scrollable. 

Conclusion: The 'modal-open' class must not be removed when the child modal has been closed.

**Comment by dwmkerr** [comment]
If this is a bootstrap modal then you'll have to do something custom, currently bootstrap doesn't support more than one modal on the screen at once:

http://getbootstrap.com/javascript/#modals

Sorry about that!
