### ISSUE TITLE
after.after is not a function

### ISSUE THREAD

**Issue by cdiaz** [dwmkerr/angular-modal-service#112]
TypeError: after.after is not a function
    at a (angular-modal-service.js:57)

**Comment by christianhanvey** [comment]
you need to include the animate module eg
```javascript
var app = angular.module('sampleapp', ['angularModalService', 'ngAnimate']);
```

**Comment by qcx** [comment]
The error keeps happening even after adding ngAnimate

**Comment by danielj86** [comment]
Same here,
Error still occurs after adding ngAnimate

**Comment by front-thinking** [comment]
same error here.
Anyone got the answer?

**Comment by front-thinking** [comment]
The error disappeared when I change  ("angular-modal-service": "~0.6.9") to ("angular-modal-service": "0.6.9")  in bower.json. Dont know why. Have a try. @danielj86 @qcx @cdiaz

**Comment by javierburger** [comment]
I got the same error ... It seems regards to the version of AngularJS , I upgraded to 1.5.8 and it works well ...

**Comment by valsouche** [comment]
remove "~" on angular-modal bower version fix my problem too.
Thanks

**Comment by olifer655** [comment]
```
Your current PostCSS version is 5.2.17, but postcss-nested uses 6.0.8. Perhaps this is the source of the error below.
```
but actuality，PostCSS version is 6.08
