### ISSUE TITLE
ModalService not working

### ISSUE THREAD

**Issue by AndreeaDora** [dwmkerr/angular-modal-service#113]
After the changes for the new release the ModalService is not working. Using the $templateRequest to handle the template caching automatically does not work.

**Comment by soninob** [comment]
+1

**Comment by liamtarpey** [comment]
+1

**Comment by lookapanda** [comment]
+1

**Comment by kenschenke** [comment]
Try a newer version of Angular.  I was getting the same error with version 1.2.21.  I updated my app to use version 1.4.9 and the error went away.
