### ISSUE TITLE
jsfiddle example is broken

### ISSUE THREAD

**Issue by axelson** [dwmkerr/angular-modal-service#114]
http://jsfiddle.net/dwmkerr/8MVLJ/

This is the primary error in the console:

    Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=%24templateRequestProvider%20%3C-%20%24templateRequest%20%3C-%20ModalService

Probably related to #113

**Comment by alexanderzeillinger** [comment]
Works if you link to latest Angular release (1.4.8 atm) instead of 1.2.9.

**Comment by dwmkerr** [comment]
Fixed, thanks for the heads up :smile:
