### ISSUE TITLE
Close any open modal back key

### ISSUE THREAD

**Issue by napcat** [dwmkerr/angular-modal-service#115]
How can I close any open modal?

I use this on a mobile app, and i have a problem. If the user press the soft or hard android back key the modal stays open, and I want it to close. If there was I method on the service to close all open modals, I could easily use it on the back key event.

Any suggestion on this?

**Comment by kernowjoe** [comment]
@napcat I've submitted a pull request to address closing a modal on locationChange https://github.com/dwmkerr/angular-modal-service/pull/141
This will help to assist in 'normal' user flow imo, I think anything outside of this could be handled elsewhere.

**Comment by dwmkerr** [comment]
Please also see:

https://github.com/dwmkerr/angular-modal-service/releases/tag/v0.12.0

Which has the `ModalService.closeModals` API
