### ISSUE TITLE
bower install deprecated

### ISSUE THREAD

**Issue by klmdb** [dwmkerr/angular-modal-service#116]
When installing through bower I get a deprecated dst.

**Comment by rich186** [comment]
+1. Was desperately trying to get animation to work, but this is not included in the latest bower version (v0.6.9). Instead I installed from commit:

`bower install 'https://github.com/dwmkerr/angular-modal-service.git#f656ba4' --save`

**Comment by alexisgahon** [comment]
+1. Same as @rich186 (thanks btw for the command line :+1: )

**Comment by iamceege** [comment]
Was noticing the same thing. Thanks for the link in the mean time :)

**Comment by dwmkerr** [comment]
Resolved in `0.12.1`
