### ISSUE TITLE
onShow event?

### ISSUE THREAD

**Issue by tianxu0836** [dwmkerr/angular-modal-service#123]
Are there onShow and onShown events?
If I put other directive like angualrjs google map it doesn't work in side this modal service.
The angualrjs Tree control also not able to work in side this modal service.

**Comment by dwmkerr** [comment]
I don't believe there is a documented way to emit these events from custom interfaces like the modal service. In this case I would suggest the best thing to do is set properties on your controller when the modal is created, and trigger the rendering or setup of the child directives from that.
