### ISSUE TITLE
does not support ng-strict-di

### ISSUE THREAD

**Issue by jalexanderfox** [dwmkerr/angular-modal-service#129]
Enabling ng-strict-di causes this service to throw errors:
[$injector:strictdi]

https://docs.angularjs.org/error/$injector/strictdi
https://docs.angularjs.org/api/ng/directive/ngApp

**Comment by jalexanderfox** [comment]
I decided to take a look at this one more time, I was able to get this working using someting like this:

```
controller: ['$scope', 'close', function($scope, close) {
```

**Comment by dwmkerr** [comment]
Cheers!
