### ISSUE TITLE
multi modal when pressing enter key

### ISSUE THREAD

**Issue by ss-bb** [dwmkerr/angular-modal-service#130]
hi. 
In any of your exemple (http://dwmkerr.github.io/angular-modal-service/). 
If you clic to open a modal, and then press 'enter' key many time, it will open as many modal as enter press time.
do you know any way to correct it? like give the focus on the modal?

**Comment by bogomips** [comment]
I have the same issue and I'm looking for a fix

**Comment by SergeyCherman** [comment]
This isn't an issue with the angular modal service but rather is based on the underlying control that is used that is the bootstrap modal.

Adding tabindex="-1" to the div containing your modal should fix the issue. I found this explanation useful: http://stackoverflow.com/questions/32911355/whats-the-tabindex-1-in-bootstrap-for
