### ISSUE TITLE
Can I use a modalController outside of a modal?

### ISSUE THREAD

**Issue by johnedvard** [dwmkerr/angular-modal-service#133]
This is not an issue, but a question, and I am sorry if this is the wrong place to ask questions. I was wondering if it is possible to use a modal-controller outside of a modal? The modal-controller injects the `close`-provider, but if I try to use the same controller in another html-file, I will get errors such as 
` Unknown provider: closeProvider <- close <- MyController`

Any best practices on how to reuse a modalController outside of a modal?

**Comment by johnedvard** [comment]
I was wondering if it is possible to "fake" a 'close'-provider when I use the controller outside of a modal, but I do not know if that is a clever thing to do, or even how to do it.

**Comment by MatteBailey** [comment]
You can do this. You can access the modal's controller from the controller you are calling `ModalService` from like so:

```javascript
ModalService.showModal({
		      ...
    }.then(function(modal) {
        modal.controller.closeModal();
	}
```

In the modal's controller:

```javascript
this.closeModal = function () {
    close(null, 400);
}
```

**Comment by johnedvard** [comment]
Thank you for the answer. The thing is, I have a controller, which takes the `close`-provider in as an argument like so:

```
angular.module('myModule')
  .controller('MyModalCtrl', function ($scope,close) {
});
```

I want to use this controller outside of a modal as well, because it contains methods that I would like to reuse. I have currently taken out many of the methods and put them in a service instead to avoid the injection error. I figured that maybe a modal controller should only live inside a modal anyways.
Thanks for the answer though
