### ISSUE TITLE
is the last version correct?

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#135]
Is the last version 0.6.10 but the last commit is tagged as 0.9.10 ?

Look at the picture, please...

![screen shot 2016-02-19 at 11 17 56](https://cloud.githubusercontent.com/assets/3993987/13172847/9b946d72-d6fa-11e5-8f0a-47addbb2bbcc.png)

**Comment by rbatllet** [comment]
What about this issue?

The version in package.json and bower.json is `0.6.10` but it's tagged with `0.9.10`

**Please, fix it!**

**Comment by dwmkerr** [comment]
@rbatllet I'm looking into it now, will fix and release ASAP

**Comment by dwmkerr** [comment]
Fixed, please move to v0.10.0
