### ISSUE TITLE
Can`t show modal window, error "Unknown Provider"

### ISSUE THREAD

**Issue by anzolo** [dwmkerr/angular-modal-service#138]
Thanx for good angular service!

But i have an error:

> Error: $injector:unpin
> Unknown Provider
> Unknown provider: closeProvider <- close <- authRegFormController
> 

error appear when i call function "showAuthRegForm".

controller calling modal window
```
remontas24Site.controller('mainController', ['$scope', 'searchMasters', 'ModalService', function ($scope, searchMasters, ModalService) {
    $scope.searchResult = searchMasters.get();

    $scope.showAuthRegForm = function () {
        ModalService.showModal({
            templateUrl: "/remontas/public/templates/modals/authRegForm.html",
            controller: "authRegFormController"
        }).then(function (modal) {
            modal.close.then(function (result) {
                console.log(result)
            });
        });
    };
}]);
```

modal controller
```
remontas24Site.controller('authRegFormController', ['$scope', 'close', function ($scope, close) {
    $scope.close = function () {
        close();
    };
}]);
```

i use angular 1.5. There may be a problem? or i do something wrong?
Help please!

**Comment by Sithdown** [comment]
+1

**Comment by anzolo** [comment]
@Sithdown i solve the problem.

The problem was in wrong controller declaration.

i declare controller in there:
```
ModalService.showModal({
            templateUrl: "/remontas/public/templates/modals/authRegForm.html",
            controller: "authRegFormController"
        }).then(function (modal) {
            modal.close.then(function (result) {
                console.log(result)
            });
```

and in the html view 

`<div ng-controller="authRegFormController">`

i think angular in this case use controller in the view. And that is the problem, because in that case in to the controller dont transfer "close".

to solve that error i clear controller declaration in the view and leave it only in showModal.

Check this situation in your project.

**Comment by Sithdown** [comment]
@anzolo Thank you, that worked for me.

**Comment by jasonwirth** [comment]
This worked for me too. Thank you. I got this with custom inputs, but also with the special `close` function that's passed into the controller.

**Comment by amberjones** [comment]
@anzolo THANK YOU.  I looked in my html and sure enough, I had ng-controller declared in there as well. Once I removed it, everything works.
