### ISSUE TITLE
bower.json contains wrong version

### ISSUE THREAD

**Issue by pv93** [dwmkerr/angular-modal-service#139]
Installing the package through bower sets the version in my bower.json file to 9.10. bower.json in repository shows version as 6.10

**Comment by fginioux** [comment]
Hi, 

I try to install the module via grunt bower and i have the following message error : 
Fatal error: Unable to find suitable version for angular

I try to change the package version number to 0.9.10 but the error still present. This my bower.json file : 
"devDependencies": {
		"bootstrap": "~3.0",
		"angular": "~1.5.4",
		"angular-route": "~1.5.4",
		"angular-sanitize": "~1.5.4",
		"angular-translate": "~2.11.0",
		"angular-ui-mask": "~1.8.2",
		"angular-validation-match": "~1.3",
		"angular-animate": "~1.5.4",
		"angular-aria": "~1.5.4",
		"angular-modal-service": "~0.9.10",
		"jquery": "~2.2.2",
		"jquery.easing": "~1.3.1"
	}

What can i do for make a clean install ? Thanks.

**Comment by rbatllet** [comment]
The tag version is wrong. The package and bower version may be correct.

**Comment by dwmkerr** [comment]
Yes it was a mistake with the tagging, I'm closing this now as I don't want to forcibly update tags which might have unexpected consequences, best bet is to update to 0.10 or upwards
