### ISSUE TITLE
modal() is undefined and modal template is appended to body

### ISSUE THREAD

**Issue by contrastlogic** [dwmkerr/angular-modal-service#14]
Code is entered exactly as the example and when the `showAModal()` function fires the modal template html is appended to the body while the console outputs this:

`TypeError: undefined is not a function`which points to this line `modal.element.modal();`

Using Angular 1.3.0
Any insight is appreciated.

Code in the controller

```javascript

			$scope.showAModal = function () {
				ModalService.showModal({
					templateUrl: 'partials/cancel-membership.modal.html',
					controller: 'ModalCtrl'
				}).then(function (modal) {

					//it's a bootstrap element, use 'modal' to show it
					modal.element.modal();
					modal.close.then(function (result) {
						console.log(result);
					});
				});
			};
```

**Comment by jonmiller1** [comment]
I'm having the same trouble.  Angular 1.3.

**Comment by satybald** [comment]
I had the same problem. Besides that you need to sure that bootstrap.js has been included into your page as pointed @dwmkerr, you also need to be sure that boostrap.js comes before angular.js. After I moved angular.js below bootstrap.js it starts working properly.

**Comment by TheKnarf** [comment]
I thought that bootstrap wasn't a dependency?

**Comment by dwmkerr** [comment]
@TheKnarf bootstrap isn't a dependency, unless you are using a bootstrap modal. There's examples in the sample app that show how to use custom modals. Bootstrap is just a very common framework that is used, but not strictly required

**Comment by dwmkerr** [comment]
Closing this issue as the solution is document in the FAQ.

**Comment by treii28** [comment]
check the load order also. My bootstrap was being pulled in in the opposite order in zend using $views->headScript()->prependFile('/path/to/script.js') in the layout. (since it is pre-pending the values, the last one prepended ends up being listed first)

**Comment by mayken** [comment]
use with Bootstrap
`$(modal.element).modal()`
