### ISSUE TITLE
Samples all point to one giant index.html

### ISSUE THREAD

**Issue by JimTheMan** [dwmkerr/angular-modal-service#142]
Is this a joke? How are people supposed to _actually_ use these modal if we have to dig through your giant index.html just to see how it's implemented...

**Comment by dwmkerr** [comment]
Not a joke. Currently I am not working on any Angular 1 projects, so any time spent on this is 100% for the community. Closing this issue in favour of https://github.com/dwmkerr/angular-modal-service/issues/73, where I will note that smaller files would be an improvement too.
