### ISSUE TITLE
Modal not showing templateurl but view is in modal state.

### ISSUE THREAD

**Issue by charliebrink** [dwmkerr/angular-modal-service#143]
I've using the sample code to show a basic modal with templateUrl and controllerAs. I'm also injecting some inputs.

On element.modal() the background goes into 'modal' state (greyed out) but the modal template / body does not show.

Inspecting the element in dev tools:
body > div.row.ng-scope.in                       <- here's my template but not showing
body > div.modal-backdrop.in

What am I missing here?

**Comment by michaelwclark** [comment]
I'm having the same issues. I have been previously using https://angular-ui.github.io/bootstrap/ UIBModal. However my build process added uglification which caused me to use explicit dependancy injection using an array:

`app.Controller('myCtrl', ['MyDep', function(MyDep){ }]);`

This seemed to break the way I was passing in parameters to my Controllers. I'm thinking this may also be an issue in this service as I'm getting undefined for my items passed into my controller.

@charliebrink are you using similar dep. injection techniques in your app? This maybe part of the issue.

**Comment by JessePimenta** [comment]
@charliebrink I'm having the same issue. after inspecting in chrome dev tools i removed the "position: fixed" style from the class modal-backdrop making the overlay dissapear, and clicked the show() button again and the modal became visible. This led to discovering that it takes me two clicks to activate the modal -- so it works, but still no success on getting it to appear in front of the backdrop on first click.

**Comment by dwmkerr** [comment]
Any chance a fiddle can be shared? Will make it much easier to debug. Closing until then as there's little for me to go on
