### ISSUE TITLE
Doesn't support ESC and click outside

### ISSUE THREAD

**Issue by tianxu0836** [dwmkerr/angular-modal-service#150]
If I enable the bootstrap click outside to dismiss modal or ESC to dismiss modal the close event will not be triggered

You will still see the modal elements still been kept in the DOM if you use the debugger to check the elements.

**Comment by tianxu0836** [comment]
I'm pretty sure this is a bug, I just tried the latest boostrap version.
It doesn't remove the modal element,it just hide it

**Comment by zzTsui** [comment]
This is a good issue, but there's no one solves this problem,god!!!

**Comment by dwmkerr** [comment]
Please see this FAQ:

https://github.com/dwmkerr/angular-modal-service#how-can-i-prevent-a-bootstrap-modal-from-being-closed
