### ISSUE TITLE
angular-google-maps not working in second modal open

### ISSUE THREAD

**Issue by Rex90** [dwmkerr/angular-modal-service#152]
I'm using angular-google-maps in the modal template. This works fine the first time the modal is opened but if i close the modal and then try to open it, the map is not rendered. I think its got something to do with the data in the controller of the modal. Does the service cache the controller or something? is there any way to disable the caching/desposing of the modal on closing the modal?

**Comment by BlackRussian** [comment]
Having this issue too

**Comment by dwmkerr** [comment]
If anyone can share a fiddle or sample I can take a look into this, but closing for now due to lack of activity
