### ISSUE TITLE
Add compatibility to Angular 1.4.x (and up)

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#154]
Could you please, remove the restriction in the bower file that only resolves to `Angular 1.4.9`?

![screen shot 2016-06-09 at 12 18 21](https://cloud.githubusercontent.com/assets/3993987/15926436/4c2c0be8-2e3c-11e6-85cc-c44deaebf58d.png)

**Comment by dwmkerr** [comment]
Yup, fixing this now

**Comment by dwmkerr** [comment]
Resolved with latest version 0.10.0
