### ISSUE TITLE
angular-modal-service.js is missing in Samples

### ISSUE THREAD

**Issue by Igor-Lopes** [dwmkerr/angular-modal-service#155]
sampleapp.js is referencing to angular-modal-service.js , which is missing by default in samples directory.

**Comment by dwmkerr** [comment]
To run the samples just clone and use:

```
npm start
```

Which should serve everything properly! Running the files without this will cause issues. I need to use webpack to make sure that the source can be kept separate from the samples and included on demand as needed.
