### ISSUE TITLE
modal.element.modal()

### ISSUE THREAD

**Issue by housemeow** [dwmkerr/angular-modal-service#160]
there is not need to call modal.element.modal() anymore.
README.md should be modified.

**Comment by vivex** [comment]
i am getting error while trying yes-no example modal.element.modal is not a function

**Comment by GiacomoK** [comment]
Same errore here

**Comment by CallumVass** [comment]
Same error here

**Comment by JosepAlacid** [comment]
Is there anybody out there?
Same error here!

**Comment by ClaytonSmith** [comment]
I too am getting this error

**Comment by thepearldream** [comment]
Just include jquery and bootstrap in your head:

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

**Comment by mdere** [comment]
Then how do we display the template as a modal if element.modal() is not needed?

I verified that modal() function does not exist for that modal.environment object returned back in the promise.

**Comment by mdere** [comment]
Actually - my solution was this issue:

https://github.com/dwmkerr/angular-modal-service/issues/14

**Comment by dwmkerr** [comment]
I think these issues are now properly covered in the FAQ, please re-open if this is not the case.
