### ISSUE TITLE
unexpected use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by angelogeminiani** [dwmkerr/angular-modal-service#162]
This error is raised under Safari both desktop and mobile using CDN.
http://cdn.rawgit.com/dwmkerr/angular-modal-service/master/src/angular-modal-service.js
"let" is no more supported
http://caniuse.com/#search=let

**Comment by ipavlic** [comment]
@angelogeminiani It's because the source code is transpiled from ES6 with babel (see webpack config). You need to use the distribute folder instead of source (http://cdn.rawgit.com/dwmkerr/angular-modal-service/master/dst/angular-modal-service.js).

**Comment by dwmkerr** [comment]
Please use the code from the `dst/` folder rather than the raw source. I have removed the `let` just in case, but you should use the transpiled code in `dst/` to be on the safe side!
