### ISSUE TITLE
Modal Closes when using bootstrap tabs inside modal

### ISSUE THREAD

**Issue by stwenter** [dwmkerr/angular-modal-service#164]
When switching tabs the same event is triggered that closes modal.  

$locationchangesuccess

Would be awesome if these two played nice and shared the ball.

**Comment by dwmkerr** [comment]
Agreed, adding this to the next release.

**Comment by aaronlifton2** [comment]
+1

**Comment by joeyramone76** [comment]
@dwmkerr I have the same problem with the new release. 
I solved this issue creating an optional parameter to make configurable the event registration:
 `var rootScopeOnClose = $rootScope.$on('$locationChangeSuccess', options.notCloseOnLocationChangeSuccess ? null : cleanUpClose);`

**Comment by dwmkerr** [comment]
Resolved in `0.13` with the `locationChangeSuccess` option: https://github.com/dwmkerr/angular-modal-service#showmodal-options
