### ISSUE TITLE
Issue when uploading to Heroku

### ISSUE THREAD

**Issue by jonaths** [dwmkerr/angular-modal-service#171]
I am using ModalService on an angular app which I uploaded to Heroku. I included the js file on the index.html file:

<script src="bower_components/angular-modal-service/dst/angular-modal-service.js"></script>

And added the dependency on the app and injected it on the controller. 

`.module('sbAdminApp', [
            'angularModalService',
            'oc.lazyLoad',
            'ui.router',
            'ui.bootstrap',
            'angular-loading-bar',
            'datatables',
            'datatables.bootstrap',
            'ui-notification',
        ])
.controller('UsersCtrl', function ($scope, $timeout, $compile, userFactory, DTOptionsBuilder, DTColumnBuilder, $q, ModalService, config, Notification) {
// Code
}`

However I keep receiving this error:

angular.js:9778 Error: [$injector:unpr] http://errors.angularjs.org/1.2.16/$injector/unpr?p0=%24templateRequestProvider%20%3C-%20%24templateRequest%20%3C-%20ModalService
    at Error (native)
    at http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:6:450
    at http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:35:431
    at Object.c [as get](http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:34:13)
    at http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:35:499
    at c (http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:34:13)
    at Object.d [as invoke](http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:34:230)
    at http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:36:13
    at c (http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:34:13)
    at d (http://young-sea-93306.herokuapp.com/bower_components/angular/angular.min.js:34:230) <div ui-view="" class="ng-scope">

The strange part is that the modal service works well while developing locally but this error appears after uploading the app to Heroku. I have checked and the .js file is loaded on the index.html file properly. Any idea on how to solve it? Thanks.

**Comment by dwmkerr** [comment]
If you can provide a zip of what you are uploading I can take a look, but closing this issue until then as this seems to be a problem with the way it is being uploaded rather than the library itself
