### ISSUE TITLE
Have problems when using a second model inside a model

### ISSUE THREAD

**Issue by Rainyhhh** [dwmkerr/angular-modal-service#176]
Here, I am using a model inside another model to implement my functions, which means to popup a model from another model. Actually it works well on the second one, but after closing the model on the top, the original model cannot scroll any more. I don't know why and wonder if any other people have the same problem.

**Comment by rbatllet** [comment]
You have to add the `modal-open` class to the body tag because when you close the second modal, it is removed.

```
    ModalService.showModal({
      templateUrl: 'myTemplate.html',
      controller: 'MyControllerCtrl',
      controllerAs: 'modalCtrl',
      inputs: {
         // my imputs
      }
    }).then(modal => {
      modal.element.modal();
      modal.close.then(() => {
        // ADD HERE AGAIN THE 'modal-open' CLASS TO THE BODY TAG
      });
    });
```

**Comment by smohammedyasin** [comment]
Same problem with me. 
for me 'modal-open' class isnot removed from body after close (second) nested modal popup.
`<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo modal-open page-overflow">`

any one found solution for this issue?

**Comment by rbatllet** [comment]
If you close the nested modal, the "modal-open" class is removed automatically. But then, the first modal cannot scroll any more. To avoid this, we need to add the "modal-open" class in the body again, and when we close the last modal without any trouble.

**Comment by dwmkerr** [comment]
Thanks for the tips @rbatllet. I'm closing this issue but leaving a reference to it here:

https://github.com/dwmkerr/angular-modal-service#problems-with-nested-modals
