### ISSUE TITLE
changing url closes modal with result

### ISSUE THREAD

**Issue by mbirnbaum** [dwmkerr/angular-modal-service#177]
When changing urls (clicking back button on browser), the modal is closes. The problem is that when checking if there is a result in the close callback, I am getting a `stateChangeSuccess` object and my callback is running.
Why is this happening? How can I either prevent the close function from firing or close with an empty result?

**Comment by rbatllet** [comment]
Add `data-backdrop` and `data-keyboard` properties:

```
<div class="modal" id="editModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
....
</div>
```

**Comment by dwmkerr** [comment]
Thanks @rbatllet!
