### ISSUE TITLE
Peticion: Angular 2 compatibility

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#179]
Is there any plans to have a version compatible with `Angular 2`?
We can not migrate to Angular 2 until available.

**Comment by HoosierWrangler** [comment]
Did this ever happen?

**Comment by rbatllet** [comment]
It seems that the current development has been stopped for some time, and I'm afraid we will never see the Angular 2 version

**Comment by dwmkerr** [comment]
On the roadmap, see also https://github.com/dwmkerr/angular-modal-service/issues/186. It all depends on how much free time I get from work unfortunately. One thing which would be useful is a note of how you want to use this in Angular 2 (e.g. what APIs would you like to be able to call, how would you like it to work in your code), then I have something to target!

**Comment by dwmkerr** [comment]
Closing in favour of #211, please put all API suggestions there!
