### ISSUE TITLE
Could  angular-modal-service work with angular 1.3.x

### ISSUE THREAD

**Issue by petervn** [dwmkerr/angular-modal-service#182]
Could  angular-modal-service work with angular 1.3.x
 i try to use with <script src="https://code.angularjs.org/1.3.5/angular.min.js"></script>
http://jsfiddle.net/dwmkerr/8MVLJ/

It dont work , why we need  angular 1.4.x version  to only show Modal dialog ???

**Comment by rbatllet** [comment]
Because the AngularJS 1.3.x is extremely old ? Why not update your AngularJs 1.3.x ? The last 1.3.9 version was released on September 30, 2015 !

**Comment by dwmkerr** [comment]
Given the date of this issue and 1.3 I am closing now, unfortunately do not have the time to attempt to support 1.3
