### ISSUE TITLE
Pressing return opens a second modal...

### ISSUE THREAD

**Issue by mikeerickson** [dwmkerr/angular-modal-service#183]
Using sample (Yes No) if I press return, instead of closing the dialog (as one would expect triggering blue yes), instead it creates another modal (and the background fade darkens)

Repeating this process continues to open another modal, and background darkens

**Comment by elliottregan** [comment]
Focusing on the newly created modal is a dangerous default. In some browsers, if the element receiving focus isn't focusable (`tabindex>=0`, `<input>`, etc.), then the focus goes to the `<body>`. If the developer wants to focus to go directly to a particular element, this would need to be coded around.

an optional `focusTarget` that uses `element.querySelector()` to search within the modal would be better. At least, that's what I've manually coded in to my controllers.

**Comment by dwmkerr** [comment]
I'm collating all issues relating to this into #209
