### ISSUE TITLE
[FEATURE REQUEST] support for angular components

### ISSUE THREAD

**Issue by sp90** [dwmkerr/angular-modal-service#186]
Is it on the roadmap to get it working with components, so instead of parsing in controller and templateurl, just to parse component name?

Example:
```javascript
ModalService.showModal({
  component: 'yesOrNo'
}).then(function(modal) {
  modal.element.modal();
  modal.close.then(function(result) {
    // Do something with the result
  });
});
```

**Comment by dwmkerr** [comment]
Yes on the roadmap, will be starting soon :)

**Comment by dwmkerr** [comment]
Closing in favour of #211, please put all API suggestions there!
