### ISSUE TITLE
No examples for using appendElement?

### ISSUE THREAD

**Issue by axx** [dwmkerr/angular-modal-service#19]
Hi,

I'd like to see an example for using the appendElement in the call to showModal().  Could you add it to the examples? :-)

Cheers,
Allister

**Comment by droptheplot** [comment]
Like this.
```javascript
appendElement: angular.element(document.getElementsByClassName('container'))
```

**Comment by dwmkerr** [comment]
If others have the same issue I'll add more to the samples, but I think the documentation is fairly clear on this one!
