### ISSUE TITLE
problem with datepicker in complex form demo

### ISSUE THREAD

**Issue by rzorzorzo** [dwmkerr/angular-modal-service#191]
hello,

i am using:
https://github.com/g00fy-/angular-datepicker

when clicking on the date field the complete modal window is removed. no exceptions are thrown.

to reproduce change the complex demo by setting for one of the form fields:

`<input type="text" class="form-control" id="name"    ng-model="dt.date"
		    date-time date-time format="DD.MM.YY" view="date" min-view="date"
											auto-close="true" 
											name="start" required="true" ng-pattern="/^(\d{2}).(\d{2}).(\d{2})$/"
											>`

**Comment by dwmkerr** [comment]
I think this might be an issue with the datepicker library, as it is seemingly only present when this library is included.
