### ISSUE TITLE
Default `appendElement`

### ISSUE THREAD

**Issue by elliottregan** [dwmkerr/angular-modal-service#192]
If there isn't a way to set a default `appendElement`, that would be a great feature. It is probably pretty common that if you define a particular `appendElement` element that you will always want to append to that element.

**Comment by wojo1206** [comment]
By default modal is appended into body. Change body var for your need line in angular-modal-service.js:46

```php
//  Get the body of the document, we'll add the modal to this.
var body = angular.element( $document[0].body ); 
```

**Comment by elliottregan** [comment]
@wojo1206 That would work, but then I would need our own fork of `angular-modal-service` and couldn't keep it updated with bower.

**Comment by dwmkerr** [comment]
This is available, see `appendElement` at: https://github.com/dwmkerr/angular-modal-service#showmodal-options
