### ISSUE TITLE
Let Keyword on angular-modal-service.js (line no 3) is not supported on safari 9.1 or greater. our web site not up

### ISSUE THREAD

**Issue by saravananNV** [dwmkerr/angular-modal-service#194]
Hey Team,

    This is saran.we have used your angular modal on our application.on the third line of  angular-modal-service.js  there was declaration of 'let' keyword.That keyword was not supporting on safari 9.1 or greater than it.safari throws error and our site is not up.is there is any alternative way to fix that

**Comment by CMUK** [comment]
I had the same issue with IE9, I changed the let to a var to fix this but have not tested in safari

**Comment by dwmkerr** [comment]
Please use the code in the `dst/` folder, which is transpiled for maximum compatibility. I have removed `let` from the source, but it doesn't guarantee you won't find other issues. Consumers should use `dst/`, `src/` is just for changing the actual project code.
