### ISSUE TITLE
seems like its not working in Sarafi browser

### ISSUE THREAD

**Issue by Subhabb** [dwmkerr/angular-modal-service#195]
Its giving error on angular modal dialogue js file (i.e angular-modal-service.js). 
Its saying "[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (angular-modal-service.js:3)"
as let keyword is not supported in sarafi 9.0 or higher.

If we are changing the 3rd line of the file 
let module = angular.module('angularModalService', []);
to
var module = angular.module('angularModalService', []);

its working perfectly fine.

**Comment by dwmkerr** [comment]
Please use the code in the `dst/` folder, which is transpiled for maximum compatibility. I have removed `let` from the source, but it doesn't guarantee you won't find other issues. Consumers should use `dst/`, `src/` is just for changing the actual project code.

**Comment by Subhabb** [comment]
Ok, thank you. I will check that
