### ISSUE TITLE
Nested(child) Popup Close Issue

### ISSUE THREAD

**Issue by smohammedyasin** [dwmkerr/angular-modal-service#199]
Hello

I'm using nested model popup, which means to popup a model from another model. Actually it works well , but the second one after closing the model on the top, the original model cannot scroll, and completely freeze .

to work validations i'm not using `data-dismiss="modal"`

if i use  ` $element.modal('hide');` it will work fine, but if i use `close('result', 500);` then parent popup will freeze(no buttons work, no scroll) 
and also a class append to html tag `<html class="modal-open">` after close nested popup

Is there any solution found? if any other people have the same problem.?

**Comment by dwmkerr** [comment]
I think this a limitation with Bootstrap: 

https://v4-alpha.getbootstrap.com/components/modal/#how-it-works

> Nested modals aren’t supported as we believe them to be poor user experiences.
