### ISSUE TITLE
Needing a way to close the modal on route change

### ISSUE THREAD

**Issue by bentedder** [dwmkerr/angular-modal-service#202]
Trying to find a good way to close this modal on route change or in some other capacity when I don't have access to the instance of the modal. Is there a way to target the modal and close it from far away?

**Comment by unkillbob** [comment]
Would this help? https://github.com/dwmkerr/angular-modal-service/pull/189

**Comment by dwmkerr** [comment]
Currently in progress

**Comment by dwmkerr** [comment]
Please check out:

https://github.com/dwmkerr/angular-modal-service/releases/tag/v0.12.0

Which I think gives you exactly what you need with:

```js
ModalService.closeModals(result, delay);
```
