### ISSUE TITLE
Latest Release Breaks CSP Rules

### ISSUE THREAD

**Issue by tylerFowler** [dwmkerr/angular-modal-service#204]
The latest release distribution has [this line:](https://github.com/dwmkerr/angular-modal-service/blob/master/dst/angular-modal-service.js#L49)

```js
var __cov_LJ6y9QsEYJy7cg83eFQGGg = Function('return this')();
```

Along with a bunch of paths to someone's local Windows machine, I assume that it was simply introduced by mistake but when you combine this line with sensible CSP rules browsers will complain that `script-src: 'unsafe-eval'` needs to be enabled.

**Comment by dwmkerr** [comment]
Not sure this is still an issue (at least with v0.12). Closing now but please re-open if you still face challenges.
