### ISSUE TITLE
IE 11 compatible?

### ISSUE THREAD

**Issue by mdere** [dwmkerr/angular-modal-service#206]
Prospecting this library for a project and wondering if this has been fully tested for IE11?

**Comment by atentis** [comment]
It is working in ie11 for me but I had to change the first declaration in the library from "let" to "var"

**Comment by dwmkerr** [comment]
@mdere @atentis should be compatible as I use webpack to transpile everything to vanilla javascript. Am closing this issue now but shout out if you are still seeing problems!
