### ISSUE TITLE
modal dismiss

### ISSUE THREAD

**Issue by hmit208** [dwmkerr/angular-modal-service#225]
i'm trying to close the modal when clicking outside it. But the modal is only hidden, and the code still exist. And if i open it again, it will be duplicated. I've tried your tip like: 
`ModalService.showModal({
  templateUrl: "some/bootstrap-template.html",
  controller: "SomeController",
  preClose: (modal) => { modal.element.modal('hide'); }
}).then(function(modal) {
  // etc
});`
but it sitll doesn't work. Can you give me some adivces. Thanks a lot

**Comment by changhuixu** [comment]
Same issue here. "close" promise doesn't remove DOM. Not sure why.
I do see it works well in demo page (http://dwmkerr.github.io/angular-modal-service/)...

**Comment by whitefox920** [comment]
Probably you've attached some kind of `$on on $rootScope` and listener isn't destroyed - in my case it was `socket.on` of socket.io. See answer in this question: https://stackoverflow.com/questions/26487365/angularjs-ui-bootstrap-scope-not-disposed-after-modal-dismiss

**Comment by dwmkerr** [comment]
Thanks to @decherneyge this is now in the bootstrap sample, so closing this issue now. Please re-open if needed!
