### ISSUE TITLE
Modal not getting closed

### ISSUE THREAD

**Issue by NicoJuicy** [dwmkerr/angular-modal-service#234]
I have seen the other comments, ending in #225 

But i don't have a $on on $rootScope, so that shouldn't be the problem.

My modal is getting called multiple times on close/hiding. Eg. [http://beta.belgianbrewed.com/en/product/budweiser-24x30cl](Example page)

The file in question can be found on /assets/angular/controllers/ShopActionController.js

I cross posted my question on [StackOverflow ](https://stackoverflow.com/questions/48817532/angular-service-modal-not-closing-properly)( my previous question with the same problem was dated 1 month ago)

**Comment by smohammedyasin** [comment]
@NicoJuicy,  I have same issue, i don't use $on or $rootScope.
did you solved the issue?

**Comment by decherneyge** [comment]
You need to add your bootstrap modal hidden listener to the dialog controller context. 

```
app.controller('ShopActionDialogController', ['$scope', '$element', 'CurrentProduct', 'close', function ($scope, $element, CurrentProduct, close) {

$scope.CurrentProduct = CurrentProduct;
console.log("Dialog called and ...");
console.log(CurrentProduct);


//modal.element.modal();

//modal.close.then(function (result) {
//    $scope.message = result ? "You said Yes" : "You said No";
//});

//listen for when the modal is dismissed and resolve the ModalService Close promise
        $element.on('hidden.bs.modal', function (e) {

            close({
                currentProduct: CurrentProduct
            }, 200); // close, but give 200ms for bootstrap to animate
        });

}]);

```

**Comment by dwmkerr** [comment]
Thanks to @decherneyge this is now in the bootstrap sample, so closing this issue now. Please re-open if needed!
