### ISSUE TITLE
request: make it compatible with AngularJS 1.7

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#263]
Using bower, it shows the following alert:
```
├─┬ angular-modal-service#0.15.1
│ └── angular#1.7.8 incompatible with 1.5.0 - 1.6.x (1.6.11-build.5555+sha.45879a8 available, latest is 1.7.8)
```
It works great with AngularJS 1.7.8. Please, remove the restriction about from 1.5.0 to 1.6.x versions and include the 1.7.x.

**Comment by dwmkerr** [comment]
Resolved in #264, released as:

```
angular-modal-service@0.15.2
```

Thanks for the heads up!
