### ISSUE TITLE
Nested calls to modal dialogs cause grayed background that never goes away..

### ISSUE THREAD

**Issue by wuntusk** [dwmkerr/angular-modal-service#27]
Anyone else have the problem of calling showModal from inside the then function of the close promise?  I get a darkened background that gets darker with the nested dialog and then never goes away.

**Comment by dwmkerr** [comment]
If this is for a Bootstrap modal then I'm afraid it's an issue with Bootstrap:

http://getbootstrap.com/javascript/#modals

As documented, multiple open modals are not supported, sorry about that!
