### ISSUE TITLE
Unknown provider: closeProvider <- close

### ISSUE THREAD

**Issue by pranspach** [dwmkerr/angular-modal-service#29]
Oddly enough, I've used angular-modal-service successfully in other projects, but haven't been able to pinpoint why this project is special. I'm not using bootstrap in any of the projects.

I'm getting this error using 0.3-0.5

Controller:
```
    .controller('SettingsCtrl', ['$scope', 'close', function ($scope, close) {
        $scope.close = function(result) {
            close(true);
        };

        $scope.cancel = function() {
            close();
        };
    }])
```

Launch point:
```
angular.module('settings',
    [
        'angularModalService'
    ])
.controller('CoreCtrl', ['$scope', '$window', 'ModalService',  function($scope, $window, ModalService){
        $scope.openSettingsDialog = function() {
            ModalService.showModal({
                templateUrl: 'markup/settings.html',
                controller: 'SettingsCtrl'
            }).then(function(modal){
                modal.close.then(function(result) {

                });
            });
        };
}])
```

**Comment by pimmey** [comment]
I was wondering how was this resolved? I'm having the same issue. If I remove the 'close' injection, the modal opens, but it's not possible to close it afterwards.

**Comment by pranspach** [comment]
I think that I was referring to the wrong function in my HTML. I was using "cancel" instead of "close" in my ng-click. Stupid typo -- I had not created the cancel function yet -- hopefully your problem is the same.

**Comment by ipavlic** [comment]
I still don't get it. `close` isn't defined anywhere in the sample, so how can it be injected?

**Comment by ChrisNelsonPE** [comment]
I'm having the same problem and I don't see a resolution, either.  Adding `ng-click="close()"` to the template shouldn't create a provider, should it?

**Comment by AChaoZJU** [comment]
@ipavlic  Do you know how can `close` be injected now ?
