### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Pepelo** [dwmkerr/angular-modal-service#30]
@dwmkerr, it'd be really great if you can publish this to npm. Since you already have package.json, it is really easy. Here are the simple steps:

  1. `cd` to your local repo
  1. `npm adduser` (and enter your info/creds (don't worry if you don't have an account)... these are the same info/creds that will log you in to npmjs.com)
  1. `npm publish`

That's it! :smile: 
Demo video: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by dwmkerr** [comment]
Hi @pepelo, it's done :)

Just out of interest, what's the use case for this? Is it simply as an alternative to bower for installing the library clientside? I can't imagine the JS being useful in a nodejs application

**Comment by Pepelo** [comment]
It is indeed just an alternative to bower for installing the libraries/packages. The libs don't have to be node modules.

**Comment by Pepelo** [comment]
...and thank you very much for the npm-publish! :smile:

**Comment by dwmkerr** [comment]
Cool thanks for the info @Pepelo :)

**Comment by benib** [comment]
this `npm publish` needs to be done for every released version. So you may want to either do this manually after you pushed the new tag or somehow integrate in in your workflow. Otherwise people installing your module with npm will get old versions (currently 0.5.0)

**Comment by dwmkerr** [comment]
@benib cheers I'll raise a task to integrate this into the release workflow :)
