### ISSUE TITLE
Need API to Close Modals

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/angular-modal-service#33]
See comment at:

http://www.dwmkerr.com/the-only-angularjs-modal-service-youll-ever-need/#comment-1810738299

It would be useful to have an API such as:

``` js
modalService.closeModals();
```

which simply closes any open modals. A potential use case is in the application router, where changing a URL should not leave the modal open. Even better would be:

``` js
modalService.closeModals(someValue);
```

Which would close all the modals and resolve their close promises with the value `someValue`. This would allow application developers to decide whether they want to allow consumers of modals to be able to handle the cases where they are closed externally explicitly.

**Comment by cointilt** [comment]
+1

**Comment by chris-hanson** [comment]
+1

**Comment by eyoung1980** [comment]
+1

**Comment by Artforge** [comment]
+1

**Comment by mbarre** [comment]
+1

**Comment by skolsuper** [comment]
+1

**Comment by klindberg** [comment]
+1

**Comment by jdrorrer** [comment]
+1

**Comment by bushiko** [comment]
I needed to close an opened modal every time an ui router stateChange event fires. I ended up writing a decorator to keep track of opened modals promises:

<pre>
  var decorator = function($delegate, $rootScope) {
    var ModalList = [];

    var originalShow = $delegate.showModal;
    $delegate.showModal = function(args) {

      // showModal retorna una promesa,
      // guardaré la lista de promesas para poderlas cerrar
      var promise = originalShow.apply(null, [args]);

      ModalList.push(promise);

      return promise;
    };

    $rootScope.$on('$stateChangeSuccess', function(event) {
      ModalList.forEach(function(modalPromise) {
        modalPromise.then(function(modal) {
          console.log('closing modal due to state change...');
          modal.element.modal('hide');

           // Remover de la lista
          var idx = ModalList.indexOf(modalPromise);
          ModalList.splice(idx, 1);
        })
      });
    });

    return $delegate
  }

  return decorator;
</pre>


and added like this in my module config phase:

<pre>
$provide.decorator('ModalService', decorator);
</pre>

**Comment by imziyang** [comment]
+1

**Comment by infodark** [comment]
+1

**Comment by paulashton** [comment]
+1

**Comment by lorenzodianni** [comment]
News?

**Comment by dwmkerr** [comment]
Hi everyone, I'm starting on this now!

**Comment by dwmkerr** [comment]
The easiest way (as of [0.12]9https://github.com/dwmkerr/angular-modal-service/releases/tag/v0.12.0) is to do this with a preClose hook:

```js
ModalService.showModal({
  templateUrl: "some/bootstrap-template.html",
  controller: "SomeController",
  preClose: (modal) => { modal.element.modal('hide'); }
}).then(function(modal) {
  // etc
});
```

Apologies for the delays everyone, it's hard to find time to work on my open source projects when I'm super busy at work!
