### ISSUE TITLE
Automate release workflow

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/angular-modal-service#36]
We need to publish to npm on release as well as bumping version numbers

**Comment by benib** [comment]
@dwmkerr can you maybe do a `npm publish` now to push 0.6.0 until this issue is resolved? Thanks for your effort.

**Comment by dwmkerr** [comment]
@benib done :smile:

**Comment by benib** [comment]
thanks. I stumpled upon this package that seems to do a good job: https://github.com/boennemann/semantic-release

**Comment by dwmkerr** [comment]
Ideal solution:

1. Use webpack for everything dev relating.
2. During dev, build to the `build` folder, not the `dst` folder.
3. All samples can use the webpack dev server (less code!)
4. One dedicated task to build to the `dst` folder.

This way PRs don't need to include `dst` changes and they'll be easier to merge.
