### ISSUE TITLE
Compatibility issue with angular-google-places-autocomplete

### ISSUE THREAD

**Issue by walbell** [dwmkerr/angular-modal-service#38]
Hi, I would like to create a modal view with an input suggesting places from google maps api.
Previously to do that I used the angular-google-places-autocomplete library (https://github.com/kuhnza/angular-google-places-autocomplete/), but now when I try to integrate it with the modal it does not work.

What I did is to modify the angularModularService in this way:
```javascript
var module = angular.module('angularModalService', ['google.places']);
```
but it didn't worked.

**Comment by dwmkerr** [comment]
Hi @walbell there should be no need to modify the angular modal service code at all, it's your own modules which will need to depend on `google.places`. Then you use the angular modal service as usual to create a modal, and in the modal controller use the `google.places` module.

**Comment by walbell** [comment]
Thanks, it worked :+1:

**Comment by dwmkerr** [comment]
Great! I'll close the issue now, glad it worked :smile:
