### ISSUE TITLE
how to use ngAnimate with custom modal ?

### ISSUE THREAD

**Issue by alepee** [dwmkerr/angular-modal-service#39]
Hi!
I do not find any way to make use of ngAnimate on modal open. The close method allow to specify a time in millisecond for this

Thanks

**Comment by alepee** [comment]
I finally did it without ngAnimate service.

**Controller**

```coffee
myApp.controller 'ModalConfirmController', ($scope, $timeout, $element, inputs, close) ->

  angular.extend $scope, inputs

  $scope.id ?= 'modal-default'
  $scope.backdrop ?= true
  $scope.display = true

  # remove class `modal-animate-enter` after modal render
  # (I am still looking for a way to do it with something like `Modal.open().then`)
  $timeout ->
    $element.removeClass 'modal-animate-enter'
  , 300

  $scope.close = (result) ->
    $element.addClass 'modal-animate-leave'
    $timeout ->
      $scope.display = false
      close result
    , 500

```

**Comment by dwmkerr** [comment]
Thanks for sharing your code, I'll leave this issue open for now so others can find it easily.

**Comment by LunarDevelopment** [comment]
It'd be nice to have a version of this code written in standard typing, I'm assuming this is typescript or coffee script or some extended syntax I'm not familiar with.. :<

**Comment by alepee** [comment]
@LunarDevelopment yes javascript is written in coffee, css in sass and html with slim.
Here is the javascript part, [compiled by js2.coffee](http://js2.coffee/#coffee/try:myApp.controller%20'ModalConfirmController'%2C%20(%24scope%2C%20%24timeout%2C%20%24element%2C%20inputs%2C%20close)%20-%3E%0A%0A%20%20angular.extend%20%24scope%2C%20inputs%0A%0A%20%20%24scope.id%20%3F%3D%20'modal-default'%0A%20%20%24scope.backdrop%20%3F%3D%20true%0A%20%20%24scope.display%20%3D%20true%0A%0A%20%20%23%20remove%20class%20%60modal-animate-enter%60%20after%20modal%20render%0A%20%20%23%20(I%20am%20still%20looking%20for%20a%20way%20to%20do%20it%20with%20something%20like%20%60Modal.open().then%60)%0A%20%20%24timeout%20-%3E%0A%20%20%20%20%24element.removeClass%20'modal-animate-enter'%0A%20%20%2C%20300%0A%0A%20%20%24scope.close%20%3D%20(result)%20-%3E%0A%20%20%20%20%24element.addClass%20'modal-animate-leave'%0A%20%20%20%20%24timeout%20-%3E%0A%20%20%20%20%20%20%24scope.display%20%3D%20false%0A%20%20%20%20%20%20close%20result%0A%20%20%20%20%2C%20500%0A)

**ModalController**
```javascript
  myApp.controller('ModalConfirmController', function($scope, $timeout, $element, inputs, close) {
    angular.extend($scope, inputs);
    if ($scope.id == null) {
      $scope.id = 'modal-default';
    }
    if ($scope.backdrop == null) {
      $scope.backdrop = true;
    }
    $scope.display = true;
    $timeout(function() {
      return $element.removeClass('modal-animate-enter');
    }, 300);
    return $scope.close = function(result) {
      $element.addClass('modal-animate-leave');
      return $timeout(function() {
        $scope.display = false;
        return close(result);
      }, 500);
    };
  });
```

**Comment by dwmkerr** [comment]
#93 now holds context on this ongoing issue, please move conversations to that thread!
