### ISSUE TITLE
Memory Leak of Single Instance of Modal

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/angular-modal-service#4]
It seems the `inputs.close` is leaked. Use a memory leak tag on the created scope to see the issue.

**Comment by dwmkerr** [comment]
I am working on a simple application to show how to resolve memory leaks and during development of that application found that:

https://github.com/dwmkerr/angular-modal-service/blob/master/src/angular-modal-service.js#L90

may be the cause of this bug. Replacing `$timeout` with `settimeout` fixes the issues, however I think consumers would expect a digest after their code. So ideally we should `cancel` the timeout, hopefully this will fix the issue.

**Comment by matthiasdailey-ccri** [comment]
Here's a permalink, since that link to master has changed over time:
https://github.com/dwmkerr/angular-modal-service/blob/315b7bbbde5a555ba8c49271520cf835963d330d/src/angular-modal-service.js#L90
