### ISSUE TITLE
Howto test the ModalController ?

### ISSUE THREAD

**Issue by campa** [dwmkerr/angular-modal-service#40]
Hi can you help me writing unit test for modal controllers ?

I tried but I'm not able to solve these errors:
- Error: [$injector:unpr] Unknown provider: $elementProvider <- $element <- PartsEditmenudialogctrlCtrl
  Or
- Error: [$injector:unpr] Unknown provider: closeProvider <- close <- PartsEditmenudialogctrlCtrl

PLease, can you add a controller test to your complexcontroller example ?

My interesting part of the test code is: 

``` javascript
beforeEach(inject(function ($controller, $rootScope) {    
    scope = $rootScope.$new();
    PartsEditmenudialogctrlCtrl = $controller('PartsEditmenudialogctrlCtrl', {
      $scope: scope
    });
```

and for the controller

``` javascript
.controller('PartsEditmenudialogctrlCtrl', [ '$route', '$scope' , '$log', 'growl', 'MainMenuService', '$element', 'close', 'currMainMenuEditData', 
                                               function ($route, $scope, $log, growl, MainMenuService, $element, close, currMainMenuEditData) {
```

Thanks in advance
Stefano

**Comment by dwmkerr** [comment]
I'll write up a quite tutorial ASAP @campa and then update this article, (@dwmkerr see also #7)

**Comment by sajadghobadi** [comment]
@campa  : you solve problem ?

**Comment by sajadghobadi** [comment]
first define below line
 var element = angular.element('<div></div>');

 hadithListCtrl = $controller('hadithListCtrl', {      
      $element:element
    });

after write mentioned lines in before function you donot see this error

**Comment by PratibhaP** [comment]
I also have the same issue, the only difference is that using custom modal, so, I don't need a $element.

Error: [$injector:unpr] Unknown provider: closeProvider <- close <- changePasswordController

while running unit testing. Can you help please me. Stuck here.

Thank you in advance.

**Comment by dwmkerr** [comment]
Closing this issue and incorporating into #10
