### ISSUE TITLE
.modal-open still attached to body after modal is closed

### ISSUE THREAD

**Issue by skylve** [dwmkerr/angular-modal-service#41]
Everytime I open a modal, .modal-open is still attached to the body of my page.
The `overflow: hiddden` property prevent me to slide my page after a modal is opened.

View:
```
<div class="modal fade">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" ng-click="close(false)" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{params.title || 'Are you sure ?'}}</h4>
      </div>
      <div class="modal-body">
        <p>
          {{params.text || 'Really ?'}}
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-white" ng-click="close(false)" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" ng-click="close(true)" data-dismiss="modal">Save changes</button>
      </div>
    </div>
  </div>
</div>
```

Controller:
```
angular.module('app')
  .controller('ConfirmModalCtrl', function ($scope, close, params) {
    $scope.params = params;

    $scope.close = function(res) {
      close(res, 200);
    };
  });
```

Call:
```
ModalService.showModal({
        templateUrl: 'views/modals/confirm.modal.view.html',
        controller: 'ConfirmModalCtrl',
        inputs: {
          params: {
            title: 'Are you sure ?',
            text: '... bla bla bla'
          }
        }
      }).then(function(modal) {
        modal.element.modal();
        modal.close.then(function(res) {
           console.log(res);
        });
      });
```

I have seriously no idea where it could come from.
I've already checked all dependencies and they are fine (bootstrap, angular, ModalService)

**Comment by Geeman201** [comment]
I believe this can be caused by the modal('hide') being called before the fade animation has fully completed. (http://stackoverflow.com/questions/11519660/twitter-bootstrap-modal-backdrop-doesnt-disappear)

As a quick solution removing the 'fade' class from the modal will make it work.

**Comment by dwmkerr** [comment]
Try changing the line:

```js
close(res, 200);
```

to

```js
close(res, 500);
```

and see if that helps - that'll give the animation more time to run before the modal content is destroyed.

**Comment by skylve** [comment]
Thanks @dwmkerr , it worked.
Sorry I did not try this before ...

**Comment by dwmkerr** [comment]
@skylve Great, glad it worked!

**Comment by sufleR** [comment]
I ha

**Comment by dszabo** [comment]
Cool, I've got the same issue, that is, *sometimes* the modal backdrop does not get removed from the body tag. Only sometimes ;) I had 200 msec specified in the close function. Modified to 500, and now seems to be stable! It'd be a good idea to add this to the FAQ.

**Comment by dszabo** [comment]
no, I was too quick. This still happens to me sometimes, and I don't get why.

**Comment by ionox0** [comment]
Anyone find a solution for this besides setting timeout?

**Comment by garima2510** [comment]
it is still happening. Finally I am manually removing "modal-open" from body.

**Comment by almothafar** [comment]
+1 I still have same issue

**Comment by rizwan-zakir-10p** [comment]
+1 ... As far as I have observed, when ng-class is also used on the body tag, or any element where the modal is targeted, this issue arises, otherwise it works just fine

**Comment by AjOpon** [comment]
My issue was commented html code inside the html file used by the modal. The commented HTML wasn't inside the modal tags , it was a separate enclosed div tags but was still on the html file .Once I removed the commented html div it resolved the backdrop issue

**Comment by AjOpon** [comment]
the html file was like so: 

`> 

<div class="modal fade">
...
</div >

removing the first commented part did the trick`

**Comment by pmn4** [comment]
Instead of using a timeout, a more reliable solution is to use the `promise` returned by the modal's `hide`method (or `show` method, if you are doing this in reverse). The promise is resolved when animation completes, so you can enqueue you the second animation to the end of the first.

here's a working example: https://embed.plnkr.co/iLS5H2MmY5MWZ0i8KMDM/

here's the gist:
``` javascript
  // animation is complete when the promise resolves.
  // set the initial state of the promise to resolved, so we
  // can open the modal without having to write extra code
  var modalIsAnimating = $q.resolve();
  $scope.closeModal = function() {
    modalIsAnimating = $scope.modal.hide();
  };

  $scope.openModal = function() {
    modalIsAnimating.then(function () {
      $scope.modal.show();
    });
  };
```

_(fyi: I am assuming that the issue occurs when opening the modal shortly after closing it... this is how I have experienced the issue)_

**Comment by coolfeature** [comment]
+1 same issue. In my scenario I am closing the modal and in then() launch a popover, after dismissing popover ui is unresponsive and modal-open is still attached to body...
