### ISSUE TITLE
Proper modal cleanup with Bootstrap

### ISSUE THREAD

**Issue by cehoffman** [dwmkerr/angular-modal-service#42]
I looked through the examples to see if there was already a documented way of properly cleaning up a modal that is dismissed when clicking outside the modal area. I didn't see anything and noticed there were many ng-click directives used to catch the modal closing.

Instead of attaching ng-click directives to all the elements and faking the animation time for the modal to disappear I used the events generated by bootstrap. I inserted this at the top of my controller to make sure the modal is properly cleaned up regardless of how it is closed and waits for the animation to finish. This handles clicking outside the modal to close, data-dismiss="modal", and $element.modal('hide').

``` javascript
$element.on('hidden.bs.modal', close)
```

I thought this might be useful documentation in the FAQ.

**Comment by dwmkerr** [comment]
This looks awesome, much easier than having to message around with a timeout for animations (which would coincidentally fix #4 I think. I'll look into getting this into the samples and documentation ASAP. Thanks for sharing @cehoffman

**Comment by gaui** [comment]
Awesome solution, well done! :+1:

**Comment by dwmkerr** [comment]
The easiest way (as of [0.12]9https://github.com/dwmkerr/angular-modal-service/releases/tag/v0.12.0) is to do this with a preClose hook:

```js
ModalService.showModal({
  templateUrl: "some/bootstrap-template.html",
  controller: "SomeController",
  preClose: (modal) => { modal.element.modal('hide'); }
}).then(function(modal) {
  // etc
});
```
