### ISSUE TITLE
keyboard events are directed to background page

### ISSUE THREAD

**Issue by ajoslin103** [dwmkerr/angular-modal-service#45]
When a modal is open, and the page behind it is obscured

While you cannot click on anything on that page

You can still tab to move the tab-focus around on the page -- and hit spacebar/enter to trigger the highlighted item

**Comment by dwmkerr** [comment]
Are you sure this is an issue with the angular modal service and not simply an issue with the bootstrap modal?

**Comment by ajoslin103** [comment]
I went to the bootstrap modal demo and did not see the same problem, theirs is directing the tab keys into the modal 

Your demo page has the issue of the tab key cyclng thru items on the page

AngularUI has the same problem, the tab key cycles thru items on the page

Maybe Angular is 'helping' ?

**Comment by dwmkerr** [comment]
Possibly, although it might be more that the bootstrap documentation page
has a little bit of JavaScript to stop it from happening

**Comment by ajoslin103** [comment]
I just ran thru the 1st 3 pages of google results on: bootstrap modal 

they _all_ have the same problem except for this one:

   http://codepen.io/SitePoint/pen/KkHyw

I sure hope that you can figure something out and add it to your code, I'm behind the 8-ball on a big project and your modals are otherwise working wonderfully for me...

If I can be of any help let me know!

**Comment by dwmkerr** [comment]
Just make sure that when you tab past the last focusable element you manually suppress the event and go to the first focusable element in the modal:

http://jsfiddle.net/dwmkerr/5botatz3/

You can probably event generalise to find the last focusable element in a container via a selector.

**Comment by ajoslin103** [comment]
I just went over to the AngularUI project and they have been trying to find the best solution for a while now.  [https://github.com/angular-ui/bootstrap/issues/738] 

They point out: Modal.prototype.enforceFocus() in Bootstrap 3 (which I found being called inside the Modal.show() ) and claim that it does the trick...  

Now why is that not working for everyone who uses Modal ?

**Comment by bogomips** [comment]
any news?

**Comment by joelcdoyle** [comment]
This was also a problem with Angular UI Bootstrap's modal for a while (https://github.com/angular-ui/bootstrap/issues/738) but some contributers eventually fixed it. It does not appear to be an easy task. I will take stab at it, because I need it for a custom modal that I am making. If I get it working I'll submit a PR.

**Comment by dwmkerr** [comment]
This is a challenge for many users, I am collecting all of the open issues related to this and closing them in favour of #209
