### ISSUE TITLE
scroll vanishes after close

### ISSUE THREAD

**Issue by chriship** [dwmkerr/angular-modal-service#48]
Hi,

I am using a $timeout to automatically close a modal after 1000 milliseconds. But the scroll bar does not come back into action after this. If I close by clicking on the close button (or anywhere other than the modal) then the scroll bar comes back fine. I have tested this on safari and firefox (on OS X).

I am using the following controller:

app.controller('YesNoController', ['$scope', 'title', 'close', '$timeout', function($scope, title, close, $timeout) {

	$scope.title = title;
	
	$timeout( function(){ 
		close('yes', 500); // close, but give 500ms for bootstrap to animate
	}, 1000);
	
  $scope.close = function(result) {
 	  close(result, 500); // close, but give 500ms for bootstrap to animate
  };

  }]);

**Comment by siready** [comment]
You have to properly close bootstrap modal. Please see #46.

**Comment by dwmkerr** [comment]
as mentioned by @siready, also see the [FAQ](https://github.com/dwmkerr/angular-modal-service#faq) under 'How do I close a Bootstrap modal manually?'
