### ISSUE TITLE
All of a sudden, all my modal widows are grayed out and not on the top layer.

### ISSUE THREAD

**Issue by hepaestus** [dwmkerr/angular-modal-service#52]
Just started happening today! Did something change? Any clues on why this would happen?

**Comment by dwmkerr** [comment]
What version are you currently using? Did you upgrade to v0.6.4? If so please try getting v0.6.5 which has a bugfix which might help you!

**Comment by hepaestus** [comment]
OK, that looks like it fixed it. Thanks!

**Comment by rubinovitz** [comment]
Still having this error on 0.6.5 and 0.6.6
