### ISSUE TITLE
Can't always close modal window 

### ISSUE THREAD

**Issue by hepaestus** [dwmkerr/angular-modal-service#53]
I am getting this message "Scripts may close only the windows that were opened by it.", and I can only  use the "Cancel" button to close a window. As far as I can tell I am set up exactly as it is in the sample.  Even when I use the cancel button, I get the same message but the window does close. Strange...

**Comment by dwmkerr** [comment]
That sounds really weird - are you serving your scripts from a CDN?

**Comment by hepaestus** [comment]
Nope. I am serving them from my desktop.

**Comment by hepaestus** [comment]
Would it just be easier if you could see the code? I can send you a link to my github privately.

**Comment by dwmkerr** [comment]
Closing this issue as it's not related to AMS

**Comment by jcarlos7121** [comment]
what was the problem on this?
