### ISSUE TITLE
How can i set the modal backdrop static?

### ISSUE THREAD

**Issue by fVargasg** [dwmkerr/angular-modal-service#57]
Hello,

I am testing the modals and I don't know how to set backdrop to static like the boostrap modal.

Ej:  ModalService.showModal({
      templateUrl: "complex/complex.html",
      controller: "ComplexController",
      backdrop: 'static',   <===================== here
      inputs: {
        title: "A More Complex Example"
      }
    }).then(function(modal) {
      modal.element.modal();
      modal.close.then(function(result) {
        $scope.complexResult  = "Name: " + result.name + ", age: " + result.age;
      });
    });

Thanks in advance.

**Comment by langman66** [comment]
Here's how I just figured out how to make the backdrop static.

            ModalService.showModal({
                    templateUrl: '/modal-campaign-question-editor.html',
                    controller: 'CampaignQuestionEditorModalController',
                    inputs: {
                        campaign: vm.campaign,
                        currentQuestionInDesignerMode: questionToEdit
                    }
                })
                .then(function(modal) {

                    //don't allow user to click outside of the modal.
                    modal.element.modal({backdrop: 'static'});
                    modal.close.then(function (result) {
                        if (result.actionTaken === 'Save') {
                            console.log(result);
                        }

                    });
                });

**Comment by fVargasg** [comment]
Thanks a lot. langman66

**Comment by gopal-g** [comment]
Thank you this helped.
