### ISSUE TITLE
modals closing by clicking outside not always wanted?

### ISSUE THREAD

**Issue by agscheidle** [dwmkerr/angular-modal-service#6]
I have modals that I want to force users to interact with (ie. disclosures). Is there a feature to enforce this?

**Comment by lookapanda** [comment]
Can you clarify where to add those data-attributes?

**Comment by agscheidle** [comment]
@lookapanda - those attributes are added to the modal template instance itself in the same way you'd add any attribute directive to the html code. So wherever you are declaring your modal instance in the html template, just add those two additional properties.
