### ISSUE TITLE
Bootstrap dependency?

### ISSUE THREAD

**Issue by toytonic** [dwmkerr/angular-modal-service#60]
Hi, 

thanks a lot for your this nice utitilty.

One question: What is the reason behind including a dependency to bootstrap in your bower.json? I actually don't see the need for this except the samples. I am using bootstrap-sass and as all bower dependencies get auto injected during the build of my project, I end up with 2 bootstrap versions.

Any suggestions? Much appreciated ;)

Cheers!

**Comment by dwmkerr** [comment]
Hi @toytonic it's a mistake on my part, it should be a `devDependency

**Comment by toytonic** [comment]
hey, thanks for the quick answer and of course for fixing it!

**Comment by hwswin** [comment]
Have same issue, thank you so much! And thanks for @dwmkerr again.

**Comment by dwmkerr** [comment]
Resolved in current version
