### ISSUE TITLE
Is there a Bootstrap version dependency?

### ISSUE THREAD

**Issue by apne** [dwmkerr/angular-modal-service#68]
I cannot get this to work with the latest bootstrap CSS (v.3.3.4): The modal appears but remains somewhat faded and there is not control over it. It disappears with any click.
On the other hand when using the bootstrap CSS provided in the example code, everything is fine!

Any insight on this behavior?

**Comment by vance** [comment]
I cannot get show() to work with class fade on bootstrap 3.3.5. Also,the examples have to change to modal.element.show() instead of modal.element.modal(). I created a pull request for this, but still there seems to be some functionality that has to change to accommodate 3.3.x

**Comment by FlavorScape** [comment]
I think angular UI had similar issues: https://github.com/angular-ui/bootstrap/issues/3184

**Comment by dwmkerr** [comment]
As far as I know no action required on this issue now.
