### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jlambert121** [dwmkerr/angular-modal-service#7]
Thank you for this great addition to angular, I love the flexibility and ease of use.

I am trying to write unit tests for a controller I'm using in a modal and cannot figure out how to inject the close provider into my tests since it looks like there's some angular magic going on.  Any tips to help?

``` javascript
it('should implement close()', function () {
      inject(function ($controller, $rootScope) {
        var scope;

        scope = $rootScope.$new();
        $controller('TemplateController', { $scope: scope } );

        expect(angular.isFunction(scope.close)).toBeTruthy();
      });
    }); // should implement close()
```

The controller is as simple as:

``` javascript
TimelineControllers.controller('TemplateController', ['$scope', 'close', function($scope, close) {
    $scope.close = function () {
      close('i was closed');
    };
  }]);
```

**Comment by sajadghobadi** [comment]
first define below line
```
  var element = angular.element('<div></div>');

 hadithListCtrl = $controller('hadithListCtrl', { $element:element });
```
after write mentioned lines in before function you donot see this error

**Comment by PratibhaP** [comment]
I also have the same issue, the only difference is that using custom modal, so, I don't need a $element.

Error: [$injector:unpr] Unknown provider: closeProvider <- close <- changePasswordController

while running unit testing. Can you help please me. Stuck here.

Thank you in advance.
