### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by resah** [dwmkerr/angular-modal-service#76]
Is jquery really necessary? It's considered bad practice to use jQuery in AngularJS projects afaik.

The necessity is not documented: E.g. for the Modal Object:
<blockquote>
modal.element - The DOM element created. This is a jquery lite object (or jquery if full jquery is used). If you are using a bootstrap modal, you can call modal on this object to show the modal.
</blockquote>

Please remove the dependency, if possible.

**Comment by hugotox** [comment]
I can't find in the angular docs what you are saying about jquery. Why you think that? https://docs.angularjs.org/api/ng/function/angular.element

**Comment by dwmkerr** [comment]
The modal service has no dependency on jQuery now
