### ISSUE TITLE
controllerAs not working with controller constructor

### ISSUE THREAD

**Issue by diego-cortez** [dwmkerr/angular-modal-service#77]
Supposing I want to use a constructor instead of using a registered controller, but also I want to use controllerAs property, so my code will be like:

```javascript
....
templateUrl: 'modal.html',
controller: ['close', function(close) {
    this.close = function(result) {
         close(result, 500);
    }
 }],
controllerAs: 'mv'
.....
```

This is not working for me, angular throws an error saying this:
Error: $controller:ctrlfmt
Badly formed controller string

So, I saw the code and when using controllerAs the code just concatenate:
```javascript
...
if(options.controllerAs) {
      controllerName = controllerName + " as " + options.controllerAs;
} 
...
```

Of course you cannot pass this to $controller service when using constructor function... 

Any possible solution to this?

**Comment by 4ants** [comment]
Did you manage to find solution?

**Comment by justinpinili** [comment]
if you keep the controller in it's own separate file and reference the controller by name you can do the following:

```
controller: 'nameOfController as mv'
```

this worked for me.

**Comment by dwmkerr** [comment]
Controller As syntax is now fully supported :)
