### ISSUE TITLE
Scroll is not working after closing modal.

### ISSUE THREAD

**Issue by funnybones** [dwmkerr/angular-modal-service#78]
Hello, I'm using the following code to trigger the modal :

$scope.showModal = function () {

            ModalService.showModal({
                templateUrl: "/file/agenda.html",
                controller: "AgCtrl",
            }).then(function (modal) {
                modal.element.modal()
                modal.close.then(function (result) {

                })
            })
        }

and inside controller:

$scope.close = function (result) {
                close(result, 500)
}

The problem is that when I'm closing the modal I cannot scroll in the app without refreshing.

**Comment by dwmkerr** [comment]
There's probably still an overlay visible, try and increase the timeout for the animation!
