### ISSUE TITLE
Add Angular 1.4.x support

### ISSUE THREAD

**Issue by rbatllet** [dwmkerr/angular-modal-service#85]
Could you please add support to the new Angular 1.4.x version?

Now It's tied to the 1.3.x version.

Thanks.

**Comment by clementoriol** [comment]
Agreed ! In my case, It looks like it's working well as is with angular 1.4, if I'm forcing it in some way, so I hope it souldn't be much more work than updating the bowerfile ?

**Comment by GregLarden** [comment]
Agreed, I'm using it with angular 1.4.3 with no issues for my use case.. please update bower.json file so we can manage it with bower and grunt :)

**Comment by rbatllet** [comment]
If I upgrade to Angular 1.4.x, then I need to explicitly force to use this version, but the solution is a bit "ugly" ...

**Comment by dwmkerr** [comment]
All done!

**Comment by GregLarden** [comment]
Awesome! thank you!!!
