### ISSUE TITLE
Strange behavior: controller does not accept other name

### ISSUE THREAD

**Issue by MaccerC** [dwmkerr/angular-modal-service#88]
Hi,
The controller in the samples from your site (http://dwmkerr.github.io/angular-modal-service/) only work with ng-controller="SampleController". When I try another name for this controller I get an error: "Error: [ng:areq] http://errors.angularjs.org/1.3.17/ng/areq?p0=SampController&p1=not%20a%20function%2C%20got%20undefined" 
How can?
Of course I renamed the name in both the sample.js and the html.

What am I doing wrong?
Gr. MaccerC

**Comment by dwmkerr** [comment]
Are you still having this issue, I'll close if not as I think this is in the sample only and others have not seen it

**Comment by MaccerC** [comment]
You're right: it is in the sample only.
You can close this issue.

Gr. MaccerC
