### ISSUE TITLE
.dragabble() support ?

### ISSUE THREAD

**Issue by agrawal-mohit** [dwmkerr/angular-modal-service#95]
Is it possible to make the modal drag-able ?

**Comment by dwmkerr** [comment]
Hi @agrawal-mohit this would be possible in the actual modal code, but would be out of the scope for the service, which exists only to orchestrate the creation and lifecycle of the modal. The modal itself could support dragging, but this would be a feature on the bootstrap modal or whatever custom modal people develop!
