### ISSUE TITLE
$tempateCache bug

### ISSUE THREAD

**Issue by jonasnas** [dwmkerr/angular-modal-service#98]
There is an issue with the way template caching is done. Angular uses its own template caching and it conflicts with the way it is implemented in this module. I have already fixed it with the following pull request. Basically instead of putting manually template url to the cache I replaced with built in one

https://github.com/dwmkerr/angular-modal-service/pull/97

**Comment by SaintPeter** [comment]
I experienced this issue as well, but I actually think the problem is not with `angular-modal-service` but if you have a leading slash on your loaded item:
```javascript
templateURL: '/app/item/item.html'
```
vs
```javascript
templateURL: 'app/item/item.html'
```

Here is the relevant code:
```javascript
} else if(templateUrl) {
          // check to see if the template has already been loaded
          var cachedTemplate = $templateCache.get(templateUrl);  // If this .get doesn't 
                                                                // find an exact match then
                                                                // it forces a GET below
          if(cachedTemplate !== undefined) {
            deferred.resolve(cachedTemplate);
          }
          // if not, let's grab the template for the first time
          else {
            $http({method: 'GET', url: templateUrl, cache: true})
```
