### ISSUE TITLE
"Local" form fields cannot be accessed (e.g. for validation)

### ISSUE THREAD

**Issue by rowild** [dwmkerr/angular-modal-service#99]
When building an email form, for example, and would like to validate it, there is no way to access the "local" form fields. The fields should be validated before a "Send" button is clicked, by which time the modal should not yet be closed, but instead wait for an $http response. But ng-required has no impact at all, and trying to get something like $scope.emailAddress (a form control inside the modal window that has ng-model="emailAdresse" as attribute) outside of the close button only yields undefined.

Any change you could provide a simple email form example?

**Comment by NitsanBaleli** [comment]
I'd also like to know please

**Comment by dwmkerr** [comment]
There was a bug with form fields in the controller, it is resolved now
